language: python

python:
    - "3.6"

dist: trusty

matrix:
    include:
        - python: "3.6"
        - python: "3.7"
          dist: xenial

addons:
    apt:
        packages:
            - zsh

before_install:
    - pip install setuptools_rust benchmarker
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$PATH:$HOME/.cargo/bin"
    - rustup default nightly

install:
    - pip install --verbose .

script:
    - cargo test
